[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend="setuptools.build_meta"
[project]
name = "django-zibanu"
version = "1.0.0-alpha.13"
authors = [
    {name="Mario CerÃ³n Charry", email="mario.ceron@mceron.com"}
]
description = " Zibanu Django Library."
readme = "README.md"
license = {file="LICENSE"}
requires-python = ">=3.7"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.9",
    "Development Status :: 3 - Alpha",
    "Framework :: Django",
    "Framework :: Django :: 3.2",
    "Environment :: Web Environment",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Application Frameworks"
]
dependencies = [
    "django>=3.2",
    "django-rest-framework",
    "djangorestframework-simplejwt"
]
keywords = [
    "django",
    "zibanu",
    "rest framework",
    "rest"
]
