[tool.poetry]
name = "notes-compiler"
version = "0.1.1"
description = ""
authors = ["Manuel Brea <m.brea.carreras@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
notes = "notes_compiler.main:main"

[tool.poetry.dependencies]
python = "^3.10"
Markdown = "^3.4.1"
markdown-katex = "^202112.1034"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
