[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "szifi"
version = "0.1.2"
authors = [
  { name="Inigo Zubeldia", email="zubeldiainigo@gmail.com" },
]
description = "Sunyaev-Zeldovich iterative Finder"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/inigozubeldia/szifi"
"Bug Tracker" = "https://github.com/inigozubeldia/szifi/issues"
