[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "benstats"
description = "A Python package for calculating Benford's Law statistics on images"
readme = "README.md"
requires-python = ">=3.7"
license = "MIT"
keywords = ["benford", "statistics", "image"]
authors = [
  { name = "gv-sh", email = "gv-sh@outlook.com" },
  { name = "bhaumikdebanshu", email = "bhaumikdebanshu@gmail.com" }
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "numpy",
  "opencv-python",
  "matplotlib",
  "pandas"
]
dynamic = ["version"]

[project.urls]
Documentation = "https://github.com/unknown/benstats#readme"
Issues = "https://github.com/unknown/benstats/issues"
Source = "https://github.com/unknown/benstats"

[tool.hatch.version]
path = "benstats/__about__.py"
