[tool.poetry]
name = "fastapi-crawler-scheduler"
version = "1.0.0"
description = ""
authors = ["laowang <847063657@qq.com>"]
readme = "README.md"
packages = [{include = "fastapi_crawler_scheduler"}]

[tool.poetry.dependencies]
python = "^3.7"
APScheduler = "^3.9.1"
fastapi = "^0.85.0"
fastapi-utils = "^0.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
