
[tool.poetry]
name = "opentps-core"
homepage = "http://opentps.org/"
version = "1.0.6"
readme = "README.md"
license = "Apache-2.0"
description = "Open source TPS for advanced proton therapy"
authors = ["Sylvain Deffet <sylvaindeffet@gmail.com>",
    "Damien Dasnoy <damien.dasnoy@uclouvain.be>",
    "Valentin Hamaide <valentin.hamaide@uclouvain.be>",
    "Guillaume Janssens <guillaume.janssens@iba-group.com>",
    "Kevin Souris <kevin.souris@iba-group.com>",
    "Sophie Wuyckens <sophie.wuyckens@uclouvain.be>"]
packages = [
    { include = "opentps"},
]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.23.2"
Pillow = "^9.2.0"
pydicom = "^2.3.0"
SimpleITK = "^2.1.1"
sparse-dot-mkl = "^0.8.2"
setuptools = "^61.0.0" # Required for local testing with python -m pip install -e .
pandas = "^1.4.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.1.2"]
build-backend = "poetry.core.masonry.api"

