[tool.poetry]
name = "graph-parse"
version = "0.3.0"
description = ""
authors = ["james <jamesnarayanrao@gmail.com>"]
readme = "README.md"
packages = [{include = "graph_parse"}]

[tool.poetry.dependencies]
python = "^3.10.5"
pydash = "*"
pydantic = "*"
pytest = "*"
mypy = "*"
coverage = "^6.4.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
