[tool.poetry]
name = "my_command"
version = "0.4.0"
description = ""
authors = ["Romain Bourr√© <romain.bourre@me.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.scripts]
my_command = 'my_command.my_package:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
