[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "axpy"
version = "0.0.1"
authors = [
    { name="gv-sh", email="gv-sh@outlook.com" }
]
description = "A Python package for Auxetics"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent"
]

[project.urls]
"Homepage" = "https://github.com/gv-sh/axpy"
"Bug Tracker" = "https://github.com/gv-sh/axpy/issues"