[build-system]
requires = ['setuptools>=61.0', 'setuptools_scm[toml]>=6.2']
build-backend = 'setuptools.build_meta'

[tool.setuptools_scm]
write_to = 'src/mlsgrid_api/_version.py'
local_scheme = 'no-local-version'
version_scheme = 'post-release'

[project]
name = "mlsgrid_api"
dynamic = ['version']

authors = [
  { name="captivus", email="366332+captivus@users.noreply.github.com" },
]
description = "Python library for the MLSGrid API"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
dependencies = [
  'requests',
  'python-dotenv',
  'pytest',
  'ratelimit',
  'pytz',
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[tool.setuptools.dynamic]
version = { attr = 'mlsgrid_api.version' }

[project.urls]
"Homepage" = "https://github.com/captivus/mlsgrid_api"